modLoader="javafml"
loaderVersion="[47,)"
license="PolyForm Shield 1.0.0"

[[mods]]
modId="mcaefcompat"
version="${mod_version}"
displayName="Minecraft Comes Alive Villager skin x Epic Fight Compatibility (MCAEF)"
description='''
Allows you to select and customize a Villager skin for MCA Mod while having Epic Fight, removing all the MCA rendering restrictions and adapting Epic Fight's animations to the Villager Skin. Also adds some fixes to MCA NPCs
'''

[[dependencies.mcaefcompat]]
modId="forge"
mandatory=true
versionRange="[47.4.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.mcaefcompat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"


[[dependencies.mcaefcompat]]
modId="mca"
mandatory=true
versionRange="[7.6.28-beta.10,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mcaefcompat]]
modId="epicfight"
mandatory=true
versionRange="[20.14.17,)"
ordering="AFTER"
side="CLIENT"
